services:
  hxsimplewebmultiplayerserver:
    container_name: hx-simple-web-multiplayer-server
    image: ghcr.io/spilehx/hx-simple-web-multiplayer-server:latest
    ports:
      - "8081:80"
    environment:
      FRAME_URL: "https://spilehx.github.io/hx-simple-web-multiplayer-server-example-pages/basic-boilerplate.html" # URL to Client to load in iframe - if not included will load debug page
      VERBOSE_LOGGING: "true"   # "true" or "false" - Show verbose logging